Name: installing mongodb component
hosts: mongodb
Become: yes
Tasks: 

  -name: print
  ansible.builtin.debug:
    msg: "hellloooo"
     
  -name: copying repo file
   ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongo.repo

  -name: install mongodb
   ansible.builtin.yum:
    name: mongod-org
    state: installed