Name: installing mongodb component
hosts: mongodb
Become: yes
Tasks: 

  -name: print
  ansible.builtin.debug:
    msg: "hellloooo"

  #

  -name: install mongodb
   ansible.builtin.yum:
    name: mongod-org
    state: installed